### ISSUE TITLE
Uncaught Exception TypeError: int() can't convert non-string with explicit base

### ISSUE THREAD

**Issue by ebubna** [damienheiser/ha-rainforest-emu2#3]
Running hassio v7.0 / core 2021.12.4 / supervisor 2021.12.2
Trying to get this up and running and receiving the following error:

Logger: root
Source: custom_components/rainforest/sensor.py:147
Integration: rainforest (documentation, issues)
First occurred: 11:52:20 AM (1 occurrences)
Last logged: 11:52:20 AM
Uncaught thread exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/rainforest/sensor.py", line 147, in serial_read
    demand = int(xmlTree.find('Demand').text, 16)
TypeError: int() can't convert non-string with explicit base

**Comment by jschulman** [comment]
I'm getting this error as well.
